### ISSUE TITLE
warning with angular 10

### ISSUE THREAD

**Issue by jmls** [thenativeweb/uuidv4#172]
converting my project to angular 10, now I get this warning

component.ts depends on uuidv4. CommonJS or AMD dependencies can cause optimization bailouts.

I am importing like this

`import { uuid } from 'uuidv4';`

how can I remove this warning ?

**Comment by goloroden** [comment]
Hi @jmls 👋 

Since I don't have any experience with Angular. I can't tell what the problem is – however, it sounds more like a configuration problem of the Angular application than like a problem with the `uuidv4` module.

Maybe searching Google for the error message helps.

I'm sorry that we are not able to help here.

Cheers,


Golo

**Comment by jmls** [comment]
thanks - I did a little digging and the reason the warning is now displayed is that angular now recommends using ECMAScript modules rather than CommonJS 

Would it be possible to provide ECMAScript (ES6 modules) as a distribution ?

**Comment by goloroden** [comment]
@jmls I see – glad you were able to figure it out 😊

Theoretically, of course, this would be possible. However, we are maintaining more than 100 open-source modules, and we have the very same workflow everywhere. This is the only way to keep the effort reasonably low, so unfortunately this is a "let's do it for all modules or for none" decision 😕

Right now we don't need the module to be ESM – in contrast since we are primarily working with Node.js, we need it to still be CommonJS to work for us. So it's not very probable that we will do this in the near future. Sorry 😞

**Comment by jmls** [comment]
I get that - fair enough. 

for anyone else coming across this , you can suppress the warning by adding this to your angular.json file

```
"build": {
  "builder": "@angular-devkit/build-angular:browser",
  "options": {
     "allowedCommonJsDependencies": [
        "uuidv4"
     ]
     ...
   }
   ...
},
```

**Comment by goloroden** [comment]
Thanks for your understanding and the constructive answer 👍
