### ISSUE TITLE
isUuid return true event if string is not a valid v4 uuid

### ISSUE THREAD

**Issue by ben8p** [thenativeweb/uuidv4#221]
Somewhere between version 6.1.0 and 6.2.4 `isUuid` was replaced by `validate` from `uuid` package.  

However, the two functions are not equivalent.  
Previous implementation of `isUuid` was validating that the 14th character was a '4' since this is a must for a valid uuid V4.  
Implementation of `validate` does not do this check causing a backward incompatible change.  

Maybe something to fix in `uuid` package ?

**Comment by goloroden** [comment]
Hi @ben8p 👋 

Thanks for bringing up this issue, and yes, you are correct.

However, as you already assumed, this is something that needs to be fixed in the `uuid` module, respectively I've seen that there is already a suggested solution.

As we're not further working in `uuidv4`, I'm going to close this.
