### ISSUE TITLE
No default export

### ISSUE THREAD

**Issue by sheuertz** [thenativeweb/uuidv4#40]
Hi,

I just upgraded to the latest uuidv4, and ran into trouble when using it. After looking through the changeset, I see that you no longer have a default export. Is there a reason that the default export was removed? I'm working with a large codebase, and I'd like to keep things up to date with the latest version, but I'd have to change a very large number of files to refactor to use the named exports.

Thanks

**Comment by goloroden** [comment]
Hi @sheuertz 👋 

Yes, we have removed the `default` export and replaced it by a named one. There are several reasons for this:

- When using a `default` export and loading the module using the old `require` function, you have to explicitly access the `default` property, either by destructuring or by using the dot operator, of which both is annoying.
- Using `default` exports is seen as bad practice by [TSLint](https://palantir.github.io/tslint/rules/no-default-export/).
- Using `default` exports is [bad for refactorings and tree-shaking](https://blog.neufund.org/why-we-have-banned-default-exports-and-you-should-do-the-same-d51fdc2cf2ad).
- If you have more than one thing to export, a `default` export doesn't work well. Here you need named exports anyway. We didn't want to mix things, so that some of our modules have `default` exports, while others have named exports – or even worse: Some modules have both at the same time.

So, to cut a long story short, this is why we replaced them.

However, to make things smoother for you, you should be able to do this with a simple search-and-replace, since the line of code where you `require` / `import` changes in the very same way.
